---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://github.com/github/super-linter#example-connecting-github-action-workflow
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ######################
      # Fetch dependencies #
      ######################
      - name: Fetch dependencies
        run: make deps-all

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          # TODO: as soon as code is fixed, then revert to false
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # "Note: All the VALIDATE[LANGUAGE] variables behave in a specific way. If none of them are passed, then they all default to true.
          # However if any one of the variables are set, we default to leaving any unset variable to false. This means that if you run the linter "out of the box", all languages will be checked.
          # But if you wish to select specific linters, we give you full control to choose which linters are run, and won't run anything unexpected."s
          # VALIDATE_GO: true
          VALIDATE_TYPESCRIPT_ES: true
          TYPESCRIPT_ES_CONFIG_FILE: ../../services/web-frontend/internal/.eslintrc.js
          # TODO: Add a separate lint step for libraries
          FILTER_REGEX_EXCLUDE: libraries
